config/routes.rb
Rails.application.routes.draw do
  resources :chat_rooms do
    member do
      post '/join' => 'chat_rooms#user_admit_room', as: 'join' 
      
    end
  
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'chat_rooms#index'
end

app/models/admission.rb
class Admission < ApplicationRecord
      # 양쪽에 걸침
    belongs_to  :user       # 캐시 지정 true : 자동으로 업데이트가 됨.    
    belongs_to  :chat_room, counter_cache: true  

    after_commit :user_join_chat_room_notification, on: :create    

    def user_join_chat_room_notification
                        # 채널명   이벤트명       / 어느 방에 들어갔느냐?       / json으로 바꿔줌.
        Pusher.trigger('chat_room', 'join', {chat_room_id: self.chat_room_id, email: self.user.email}.as_json)
                                                                        # show.html.erb에서 email 변수를 사용하기 위해서 넣어줌.     
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord

    has_many    :admissions
    has_many    :users, through: :admissions
    
    has_many    :chatchats
    after_commit :create_chat_room_notification, on: :create
                                            # 만들어 질 때
    def create_chat_room_notification
                        # 채널명  / 발생이벤트 / # 데이터를 보낼 곳
        Pusher.trigger('chat_room', 'create', self.as_json)
                                                # json을 통째로 넣어줌! => 인덱스에서 처리함!
                                            # 이 이벤트에 전달해줄 데이터( json 형태 )    
    end

                   # 파라미터로 넘어온 user 객체
    def user_admit_room(user)   # self가 없으므르 인스턴스 메서드
        Admission.create(user_id: user.id, chat_room_id: self.id)
        # ChatRoom이 하나 만들어지고 나면 다음 메서드를 같이 실행한다.
    end



end

app/models/chatchat.rb
class Chatchat < ApplicationRecord
    
    belongs_to :user
    belongs_to :chat_room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_many   :admission_count
         has_many   :chat_rooms, through: :admissions # admission을 통해서 채팅룸 여러개를 가질 수 있다.
         has_many   :chatchats  # 여러개의 채팅을 가질 수 있다.
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :set_chat_room, only: [:show, :edit, :update, :destroy, :user_admit_room]
  before_action :authenticate_user!, except: [:index]
        #  로그인 안했는데, 채팅방 못보게 해야함. (리스트만 볼 수 있게)
  
  # GET /chat_rooms
  # GET /chat_rooms.json
  def index
    @chat_rooms = ChatRoom.all
  end

  # GET /chat_rooms/1
  # GET /chat_rooms/1.json
  def show
  end

  # GET /chat_rooms/new
  def new
    @chat_room = ChatRoom.new
  end

  # GET /chat_rooms/1/edit
  def edit
  end

  # POST /chat_rooms
  # POST /chat_rooms.json
  def create
    @chat_room = ChatRoom.new(chat_room_params) 
    @chat_room.master_id  = current_user.email  ####
    respond_to do |format|
      if @chat_room.save
        # 아이디 부여받기     # @chat_room 인스턴스
        @chat_room.user_admit_room(current_user)    # 참여를 하게 됨.
        format.html { redirect_to @chat_room, notice: 'Chat room was successfully created.' }
        format.json { render :show, status: :created, location: @chat_room }
      else
        format.html { render :new }
        format.json { render json: @chat_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chat_rooms/1
  # PATCH/PUT /chat_rooms/1.json
  def update
    respond_to do |format|
      if @chat_room.update(chat_room_params)
        format.html { redirect_to @chat_room, notice: 'Chat room was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat_room }
      else
        format.html { render :edit }
        format.json { render json: @chat_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chat_rooms/1
  # DELETE /chat_rooms/1.json
  def destroy
    @chat_room.destroy
    respond_to do |format|
      format.html { redirect_to chat_rooms_url, notice: 'Chat room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def user_admit_room
      # 현재 유저가 있는 방에서 조인 버튼을 눌렀을 때, 들어가는 액션
      @chat_room.user_admit_room(current_user)  
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat_room
      @chat_room = ChatRoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_room_params
      params.fetch(:chat_room, {}).permit(:title, :max_count)
    end                           # title과 max_count 만 받게 되어있음
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/views/chat_rooms/_form.html.erb
<%= form_for(chat_room) do |f| %>
  <% if chat_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chat_room.errors.count, "error") %> prohibited this chat_room from being saved:</h2>

      <ul>
      <% chat_room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  
    <div class="form-group">
    <%= f.label :max_count %>
    <%= f.number_field :max_count %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chat_rooms/edit.html.erb
<h1>Editing Chat Room</h1>

<%= render 'form', chat_room: @chat_room %>

<%= link_to 'Show', @chat_room %> |
<%= link_to 'Back', chat_rooms_path %>

app/views/chat_rooms/index.html.erb
<% if user_signed_in? %>
<%= current_user.email %> / <%= link_to 'log out', destroy_user_session_path, method: "delete" %>
<% else %>
<%= link_to 'log in', new_user_session_path %>
<% end %>
<h1>Chat Rooms</h1>

<table>
  <thead>
    <tr>
      <th>방 제목</th>      
      <th>인원수</th>
      <th>방장</th>
    </tr>
  </thead>

  <tbody class="chat_room_list">
    <% @chat_rooms.reverse.each do |chat_room| %>
      <tr>
        <td><%= chat_room.title %></td> <!-- 현재 몇 명의 인원이 있는지 / 최대치 -->
        <td><span class="current<%= chat_room.id %>"><%= chat_room.admissions.size %></span>/ <%= chat_room.max_count %></td>
        <td><%= chat_room.master_id %></td>
        <td><%= link_to 'Show', chat_room %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chat Room', new_chat_room_path %>

<script>
    // function 만들기!
  $(document).on('ready', function() {
        // 방이 만들어 졌을 때, 
        // 방에 대한 데이터를 받아서 방 목록에 추가해주는 js function
        
           // 방 만들어줘 라고 작동되면 chat_room_list에 추가해주면 됨!
        function room_created(data) {
          $('.chat_room_list').prepend(`
            <tr>  //그 위치에서  // 있던 것에 더한다.
              <td>${data.title}</td> 
              <td><span class="current${data.id}">0</span>/${data.max_count}</td>
              <td>${data.master_id}</td>
              <td><a href="/chat_rooms/${data.id}">Show</a></td>
            </tr>
          `);
            alert("방이 추가되었습니다.");
          }
          
          function user_joined(data) {
            var current = $(`.current${data.chat_room_id}`);
                            //current의 text를 가져와서 인트로 바꾸고 1을 더함.
            current.text(parseInt(current.text()) + 1);
                  // 꺼내서 1씩 증가시켜줌.
          }
                        // 뭔갈 만들어서 pusher에다 넣었음.
          var pusher = new Pusher('<%= ENV["Pusher_key"] %>', {
            cluster: "<%= ENV["Pusher_cluster"] %>",
            encrypted: true
          });
                                        // 채널       //이벤트 (아래)
          var channel = pusher.subscribe('chat_room');
          
          channel.bind('create', function(data) {
            console.log(data);      //models/chat_room.rb
            room_created(data);
           });
          channel.bind('join', function(data) {
            console.log(data);    // {chat_room_id: 10}   가 확인됨!
            user_joined(data);
          });
  });
  
</script>

app/views/chat_rooms/new.html.erb
<h1>New Chat Room</h1>

<%= render 'form', chat_room: @chat_room %>

<%= link_to 'Back', chat_rooms_path %>

app/views/chat_rooms/show.html.erb
<%= current_user.email %>

<h3> 현재 이 방에 참여한 사람</h1>
<div class="joined_user_list">
    <% @chat_room.users.each do |user| %>
        <p><%= user.email %></p>
    <% end %>
</div>

<%= link_to 'Join', join_chat_room_path(@chat_room), method: 'post', remote: true, class: "join_room" %> |
<%= link_to 'Edit', edit_chat_room_path(@chat_room) %> |            <!-- ajax로 동작함-->
<%= link_to 'Back', chat_rooms_path %>

<script>
  $(document).on('ready', function() {
      
      function joined_user_list(data) {
          $('.joined_user_list').append(`<p>${data.email}</p>`);
      }
      
      var pusher = new Pusher('<%= ENV["Pusher_key"] %>', {
        cluster: "<%= ENV["Pusher_cluster"] %>",
        encrypted: true
      });
      
      var channel = pusher.subscribe('chat_room');
      
      channel.bind('join', function(data) {
          console.log(data);    // {chat_room_id: 10}   가 확인됨!
          joined_user_list(data);
      });
  });
</script>

app/views/chat_rooms/user_admit_room.js.erb
alert(" 방에 조인 함 ");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'  %>
     <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>